### ISSUE TITLE
[Questions]Features

### ISSUE THREAD

**Issue by realtica** [fltk-rs/fltk-table#10]
Hello, the table supports Horizontal scroll, cell edition, deletion?
And what about the performance for example in a 50x50 of data?

**Comment by MoAlyousef** [comment]
Hello
Yes it supports horizontal scroll, cell edition and deletion of the contents of the cell. You can also add/remove rows/columns. 
performance should be good even for large amounts of data.

It’s best that you try it to know if the performance is acceptable for you (remember to build in release mode). If not, you can use fltk’s table widget directly and optimize it for your requirements.

**Comment by realtica** [comment]
Hello and thanks, the table is very fast good job.
Is it possible to do auto width of columns or something similar to fit to content?, please see the image attached.

![fltk-table2-2022-03-21_18-31](https://user-images.githubusercontent.com/852446/159379687-1f7c1ed1-0801-4c85-8b42-c3d882345bdc.png)


![fltk-table2022-03-21_18-23](https://user-images.githubusercontent.com/852446/159379380-34de60bf-8303-4426-9744-ae22dfdaca99.png)

**Comment by MoAlyousef** [comment]
Peforming text width measurements for all data is a heavy operation for a table. You can do some heuristics by using something like fltk::draw::measure(text, true) once for the first item in each column for example, then use the width value in table.set_col_width(col, width). Or a simpler heuristic which depending on the length of the string, set_col_width to some value.

**Comment by realtica** [comment]
Hello,
Is it possible copy text from cell content with editable: false?

**Comment by MoAlyousef** [comment]
`table.input().as_mut().unwrap().set_readonly(true);`
