### ISSUE TITLE
Appending a row to an empty table panics

### ISSUE THREAD

**Issue by vstojkovic** [fltk-rs/fltk-table#14]
Running the following code panics:
```
let mut table = SmartTable::default_fill()
    .with_opts(TableOpts {
        rows: 0,
        cols: 10,
        editable: false,
        ..Default::default()
    });
table.append_empty_row("");
```

The problem seems to be that the code tries to determine the number of columns by getting the length of the vector in the first row of the data (`data[0].len()`) but `data` is empty in an empty table.

I can work around it by getting and locking `data_ref()`, but I thought I should report this anyway.

**Comment by MoAlyousef** [comment]
So I seem to have missed this issue, but it seems that the latest PR has it fixed. I've published a new version 0.2.2. If it's not fixed, please report back.
