### ISSUE TITLE
How to use select_row in fltk-table?

### ISSUE THREAD

**Issue by felixmaker** [fltk-rs/fltk-table#20]
Hi,

How can I select the whole row as I click on the cell in this row?

Here is what I did: 

I set table editable false, then add handle: 

```
table.handle(|tb, event| {
        match event {
            enums::Event::Released => {
                let (row_top, _, row_bot, _) = tb.get_selection();

                if let Err(err) = tb.select_row(row_top, table::TableRowSelectFlag::Select) {
                    println!("{}", err);
                }
            }
            _ => {}
        }
        true
    });
```

However, It does not select the row. Would it possible to make fltk-table act like browser widget?

Thank you!

**Comment by MoAlyousef** [comment]
Hello

You should be able to import the TableExt trait from fltk, and use set_selection. 

```rust
use fltk::prelude::TableExt;

tb.set_selection(row_top, 0, row_top, end_column);
```

**Comment by felixmaker** [comment]
Thank you very much! It works!
