### ISSUE TITLE
On Input Callback?

### ISSUE THREAD

**Issue by XPXPv2** [fltk-rs/fltk-table#21]
While looking through the documentation their doesn't seem to be a way of setting a callback on user input besides setting one from fltk::input::Input which would appear to break the input system. The addition of this seems to be the only clean way in certain situations besides having a third list a data to resolve conflicts. This doesn't seem hard to implement either, just storing a callback function and calling it from the existing one input system one. I would be happy to do this, but just wanted to make sure I wasn't missing the obvious.

**Comment by MoAlyousef** [comment]
Hi
I would appreciate if you could contribute this.
Thank you
