### ISSUE TITLE
Memory leak in GB

### ISSUE THREAD

**Issue by dbdante** [fltk-rs/fltk-table#25]
After almost solving the issue #24, I encountered memory leak. After troubleshooting a bit, it seems the table leaks memory and am not sure if it is originating from the rust or the C side. Without making any modifications this can be reproduced by just downloading the repo and running any of the example. The leak can be triggered by performing multiline selects over and over again. The memory usage starts increasing by KBs initially and eventually starts increasing in MBs. Below is a snapshot of the "simple" example's memory usage
![image](https://github.com/fltk-rs/fltk-table/assets/61209743/6f5777b9-35a6-4120-9891-c94403856a51)

**Comment by MoAlyousef** [comment]
Hi
I think it’s the issue here. It should be fixed in latest fltk-rs, which isn’t released yet.

**Comment by dbdante** [comment]
Thank you. I was not able to reproduce with the latest version. I will close the issue.
