### ISSUE TITLE
Cell editor positioning issue when table is inside pack.

### ISSUE THREAD

**Issue by tristan-minimax** [fltk-rs/fltk-table#26]
I have a table inside of an hpack. When editing a cell, the cell editor shows in the next hpack position (right side of screenshot) instead of on top/inside of the original cell where it should be.
![image](https://github.com/user-attachments/assets/010c93b4-e325-4cfb-b13c-909bc387374e)

**Comment by MoAlyousef** [comment]
Hello
Thanks for the report. Can you try updating to 0.3.3, I've pushed a fix and published a new version.

**Comment by tristan-minimax** [comment]
Thanks for the quick update!

Unfortunately, I am still noticing issues where the rendering for the editing mode does not happen at all, or is very sporadic. Attached are recordings of a table not in a pack and in a pack. I am unable to get the editor mode to show at all inside a pack.

No pack:
https://github.com/user-attachments/assets/467822b8-43de-42bc-8fe5-07dc2b8daede


Pack:
https://github.com/user-attachments/assets/ee61ffe3-7c2f-4fcc-be22-d7fceeeeb7e9

**Comment by MoAlyousef** [comment]
Thanks for getting back to me quickly. I’ll try to look deeply into the issue tomorrow and over the weekend 👍

**Comment by MoAlyousef** [comment]
Can you try with the latest master:
```toml
[patch.crates-io]
fltk-table = { git = "https://github.com/fltk-rs/fltk-table" }
```

**Comment by tristan-minimax** [comment]
This version is working as expected both in and out of a pack. Everything is working well.

Thank you!
