### ISSUE TITLE
Hide / show rows

### ISSUE THREAD

**Issue by jlgerber** [fltk-rs/fltk-table#4]
Use case: filtering down a table based on user input. 

It would be great to be able to hide / show row by index.

**Comment by MoAlyousef** [comment]
Currently you can use TableExt’s `set_row_height(row_num, 0);`

It would also be useful to add to the TableOpts, maybe as a slice of values and ranges.

**Comment by MoAlyousef** [comment]
Hi
The latest release also add remove_row(idx), thanks to this https://github.com/fltk-rs/fltk-table/pull/5.
