### ISSUE TITLE
SmartTable seems to create a spurious input widget

### ISSUE THREAD

**Issue by mark-summerfield** [fltk-rs/fltk-table#6]
I just want a read-only table whose values I can set programmatically.
The only user interaction I want is for the user to be able to scroll and double click (or use arrow or page up/down and press space or enter) to choose a row.

But right now I get the 3 column x 100 row table I want _plus_ an **unwanted** input widget. How can I get rid of this input widget?
[charfind.zip](https://github.com/fltk-rs/fltk-table/files/7821725/charfind.zip)
The project I'm working on that shows the problem is attached.
Thanks!

**Comment by MoAlyousef** [comment]
Hi
Unfortunately I’m out of town for 2 days, so I can’t check the zip file, ios has trouble with it. Are you passing the option `editable: false,` to TableOpts?

**Comment by mark-summerfield** [comment]
There's no hurry! Yes, I pass `editable: false`.

**Comment by MoAlyousef** [comment]
Can you try the latest main branch. I made the input optional.

**Comment by mark-summerfield** [comment]
I've already switched to using a `browser::HoldBrowser` instead of a table.
Attached is an old version that uses table. But it still has 0-based row numbers & still shows an input widget.
[charfind.tar.gz](https://github.com/fltk-rs/fltk-table/files/7833335/charfind.tar.gz)

**Comment by MoAlyousef** [comment]
The version wasn’t published yet, you’ll have to add fltk-table as a git dependency (version 0.2.0)

**Comment by mark-summerfield** [comment]
OK, the new version does start counting display rows from 1 and no input widget is shown:-)

I'm still going to persist with the `HoldBrowser` for this application though.
For the table I'd suggest having a function set_column_growable(i32) which would allow one column to be set to consume all excess horizontal space. Or, for maximum versatility set_column_weight(i32, u32) which allowed the user to set column widths proportionally.
Also it would be nice to have the choice of cell _or_ row selection.
Anyway, just for reference I've attached an updated tarball.
[charfind-table.tar.gz](https://github.com/fltk-rs/fltk-table/files/7833930/charfind-table.tar.gz)
