### ISSUE TITLE
Displayed row numbers conventionally start at 1 not 0

### ISSUE THREAD

**Issue by mark-summerfield** [fltk-rs/fltk-table#7]
Although internally we expect row numbers to start at 0, the row numbers displayed by a table conventionally start at 1. This should at least be an option.

**Comment by MoAlyousef** [comment]
I’ll add it to the opts. For the time being you can change the row header values:
```rust
for i in 0..30 {
        table.set_row_header_value(i, &i.to_string());
    }
```

**Comment by mark-summerfield** [comment]
That almost works, here's what does:-)
```rust
for i in 0..30 {
    table.set_row_header_value(i, &(i + 1).to_string());
}
```

**Comment by MoAlyousef** [comment]
Indeed :)
The latest main now starts row count at 1.
