### ISSUE TITLE
API issues

### ISSUE THREAD

**Issue by mark-summerfield** [fltk-rs/fltk-table#8]
`append_empty_row()` accepts a string but what is the string for?

Suggestions;
* `append(Vec<&str>)` -- appends a new row and puts each string into the corresponding colum; should throw an error if the vec's length is != number of columns
* `clear()` -- delete all rows & columns in the table (but ideally leaving the headers)
* `row_count() -> usize`
* `column_count() -> usize`

Even with the existing API I can't see how to clear a table of all its rows and then append new rows one by one.

_Just to let you know_: I now realise I should be using one of the `browser` widgets for my purpose, so I won't be using the `fltk_table`, at least not in the application I'm working on now.

**Comment by MoAlyousef** [comment]
The append_empty_row takes a string which is the row header, I've updated the signature to reflect that.

I've added clear(), row/column_count and append_row/append_col in the main branch.

**Comment by mark-summerfield** [comment]
Thanks for adding these.
